# -*- coding: utf-8 -*-
"""
B7 Global website content.

CONFIG  -> contact details. Leave a value as "" and the site shows a
           "Coming soon" placeholder. Fill it in, run `python3 build.py`, done.
T       -> all visible text, in English ("en") and Arabic ("ar").
"""

CONFIG = {
    "site_url": "https://b7global.ae",
    "phone": "+971 50 463 0160",   # shown on the card & company profile
    "email": "bassam@b7global.ae",
    "whatsapp": "",                # e.g. "+971504630160"     (digits only after +)
    "location_en": "United Arab Emirates",
    "location_ar": "دولة الإمارات العربية المتحدة",
    # Contact form delivery, in priority order:
    #   1. EmailJS (fill all three below)  -> enquiries land straight in the inbox
    #   2. form_endpoint (e.g. a Formspree URL)
    #   3. "email" above -> opens the visitor's email app
    # The EmailJS public key is meant to be public (it is visible in any site's source).
    "emailjs_service_id": "",
    "emailjs_template_id": "",
    "emailjs_public_key": "",
    "form_endpoint": "",
}

T = {}

T["en"] = {
    "lang": "en",
    "dir": "ltr",
    "other_lang_label": "العربية",
    "other_lang_code": "ar",
    "company": "B7 Global Brokerage Services",
    "meta_title": "B7 Global | Commercial Brokerage & Company Representation in the UAE",
    "meta_desc": "B7 Global Brokerage Services connects businesses with relevant commercial opportunities and partners through brokerage, representation, and product and service marketing, from the UAE.",
    "skip": "Skip to content",
    "nav_about": "About",
    "nav_services": "Services",
    "nav_focus": "Focus areas",
    "nav_process": "How we work",
    "nav_contact": "Contact",
    "nav_cta": "Get in touch",
    "menu": "Menu",

    "hero_eyebrow": "Commercial Brokerage • Representation • Business Connections",
    "hero_h1_a": "Connecting markets.",
    "hero_h1_b": "Creating opportunities.",
    "hero_lead": "B7 Global Brokerage Services connects businesses with relevant commercial opportunities and partners through brokerage, representation, and product and service marketing.",
    "hero_cta1": "Start a conversation",
    "hero_cta2": "Our services",
    "logo_alt": "B7 Global logo: Trade, Sourcing, Brokerage",

    "trust": [
        ("pin", "Based in the UAE"),
        ("globe", "Local & cross-border"),
        ("shield", "Confidential handling"),
        ("check", "Clear follow-up"),
    ],

    "about_eyebrow": "About the company",
    "about_title": "A clear point of contact for your commercial requests",
    "about_p1": "B7 Global Brokerage Services is a single-owner limited liability company operating from the United Arab Emirates. We support business communication and help coordinate introductions between companies, product and service providers, and prospective customers, within the scope of our licence and any applicable approvals.",
    "vision_title": "Our vision",
    "vision": "To be a trusted partner for building practical, lasting business relationships between companies in the UAE and regional and international markets.",
    "mission_title": "Our mission",
    "mission": "To make relevant commercial opportunities easier to access through clear communication, a sound understanding of business needs, and coordinated follow-up from initial introduction to agreed next steps.",
    "values_title": "Our values",
    "values": [
        "Clarity and integrity in commercial communication.",
        "Responsiveness and reliable follow-up.",
        "Understanding client needs before proposing a route forward.",
        "Respect for business confidentiality.",
        "Professional relationships built for the long term.",
    ],
    "info_title": "Company information",
    "info": [
        ("Trade name", "B7 Global Brokerage Services (S.P.S - L.L.C)"),
        ("Legal form", "L.L.C (Sole Proprietorship)"),
        ("Location", "United Arab Emirates"),
        ("Proprietor", "Bassam Mousa"),
    ],

    "services_eyebrow": "What we do",
    "services_title": "Services",
    "services_intro": "Four ways we help businesses find the right counterpart and keep the conversation moving.",
    "services": [
        ("link", "Commercial brokerage", "We introduce relevant businesses and coordinate initial communication and the exchange of agreed commercial information."),
        ("briefcase", "Company representation", "We support companies in business communication and in presenting their products and services, within the agreed authority and licence scope."),
        ("phone", "Telephone marketing", "We contact prospective customers to introduce products or services, understand initial interest, and arrange follow-up."),
        ("swap", "Services brokerage", "We connect clients with suitable service providers and help clarify the request and the next steps between the parties."),
    ],
    "licensed_label": "Licensed activities",
    "licensed": [
        "Companies Representation",
        "Marketing for Products and Services via Telephone",
        "Commercial Agent",
        "Services Broker",
    ],

    "focus_eyebrow": "Where we focus",
    "focus_title": "Focus areas",
    "focus_intro": "We direct our services towards businesses and opportunities in the following industrial and commercial areas.",
    "focus": [
        ("layers", "Metals & packaging materials", "Tinplate and other metal products, together with industrial raw materials and inputs."),
        ("gear", "Machinery & production lines", "Production equipment, machinery, production lines and industrial spare parts."),
        ("box", "Manufacturing & packaging supplies", "Manufacturing and packaging supplies and the related business services that support industrial operations."),
        ("globe", "Sourcing & distribution", "Sourcing, distribution and business cooperation opportunities in the UAE and across borders."),
    ],

    "serve_eyebrow": "Who we serve",
    "serve_title": "Built for businesses that buy, sell and represent",
    "serve_p": "We serve manufacturers, suppliers, service providers, distributors and business buyers, as well as companies seeking a commercial representative or a communication channel to develop their market presence.",
    "serve_chips": [
        "Manufacturers",
        "Suppliers",
        "Service providers",
        "Distributors",
        "Business buyers",
        "Companies seeking a commercial representative",
    ],
    "scope_title": "Geographic scope",
    "scope_p": "Based in the UAE, we support local and cross-border commercial opportunities according to each assignment, the availability of suitable parties, and applicable regulatory requirements.",

    "process_eyebrow": "How we work",
    "process_title": "A clear process from first call to next steps",
    "process_intro": "We follow simple, defined steps that organise communication and align expectations between the parties.",
    "steps": [
        ("Understand the requirement", "Confirm the product or service, the target market, and the client's key requirements."),
        ("Identify a suitable party", "Look for a supplier, customer or business partner that fits the agreed scope."),
        ("Arrange the introduction", "Coordinate an introduction and initial information exchange, with the parties' agreement."),
        ("Follow up on commercial points", "Track inquiries, documents and the commercial steps the parties agree to exchange."),
        ("Confirm next steps", "Record agreed actions and follow up with the relevant parties."),
    ],
    "expect_title": "What you can expect from B7 Global",
    "expect": [
        "A clear point of contact for the commercial request.",
        "Organised coordination between parties to reduce misunderstandings.",
        "Professional handling of confidential business information.",
        "Practical follow-up aligned with the assignment and licensed activities.",
    ],

    "contact_eyebrow": "Contact",
    "contact_title": "Let's talk business",
    "contact_p": "Tell us what you are looking to buy, sell or represent, and we will come back to you with clear next steps.",
    "c_person": "Contact",
    "c_person_v": "Bassam Mousa",
    "c_phone": "Telephone",
    "c_email": "Email",
    "c_whatsapp": "WhatsApp",
    "c_location": "Location",
    "soon": "Coming soon",
    "f_name": "Full name",
    "f_company": "Company",
    "f_email": "Email address",
    "f_phone": "Phone number",
    "f_topic": "I'm interested in",
    "f_topics": [
        "Commercial brokerage",
        "Company representation",
        "Telephone marketing",
        "Services brokerage",
        "Something else",
    ],
    "f_message": "How can we help?",
    "f_send": "Send enquiry",
    "f_sending": "Sending…",
    "f_required": "Please fill in your name, email and message.",
    "f_ok": "Thank you. Your enquiry has been sent and we will be in touch shortly.",
    "f_mailto": "Opening your email app so you can send your enquiry.",
    "f_err": "Sorry, something went wrong. Please try again or contact us by phone.",
    "f_notready": "Our online form is being set up. Please contact us by phone in the meantime.",
    "f_notready_phone": "Our online form is being set up. Please call us on {phone} in the meantime.",

    "foot_tag": "Connecting markets. Creating opportunities.",
    "foot_nav": "Explore",
    "foot_contact": "Get in touch",
    "foot_disclaimer": "The company conducts business within its licensed activities and obtains any approvals or permits required for the nature of each transaction.",
    "foot_rights": "All rights reserved.",
    "to_top": "Back to top",
}

T["ar"] = {
    "lang": "ar",
    "dir": "rtl",
    "other_lang_label": "English",
    "other_lang_code": "en",
    "company": "B7 Global Brokerage Services",
    "meta_title": "B7 Global | الوساطة التجارية وتمثيل الشركات في الإمارات",
    "meta_desc": "تربط B7 Global Brokerage Services الشركات بالفرص والشركاء التجاريين المناسبين من خلال الوساطة التجارية والتمثيل وتسويق المنتجات والخدمات، من دولة الإمارات العربية المتحدة.",
    "skip": "انتقل إلى المحتوى",
    "nav_about": "من نحن",
    "nav_services": "خدماتنا",
    "nav_focus": "مجالات التركيز",
    "nav_process": "أسلوب العمل",
    "nav_contact": "تواصل معنا",
    "nav_cta": "تواصل معنا",
    "menu": "القائمة",

    "hero_eyebrow": "الوساطة التجارية • التمثيل • بناء العلاقات التجارية",
    "hero_h1_a": "نربط الأسواق،",
    "hero_h1_b": "ونصنع الفرص.",
    "hero_lead": "تربط B7 Global Brokerage Services الشركات والجهات التجارية بالفرص والشركاء المناسبين من خلال الوساطة التجارية والتمثيل وتسويق المنتجات والخدمات.",
    "hero_cta1": "ابدأ المحادثة",
    "hero_cta2": "خدماتنا",
    "logo_alt": "شعار B7 Global: تجارة، توريد، وساطة",

    "trust": [
        ("pin", "مقرّنا دولة الإمارات"),
        ("globe", "محلي وعبر الحدود"),
        ("shield", "سرية المعلومات التجارية"),
        ("check", "متابعة واضحة"),
    ],

    "about_eyebrow": "نبذة عن الشركة",
    "about_title": "نقطة تواصل واضحة لطلباتكم التجارية",
    "about_p1": "B7 Global Brokerage Services شركة ذات مسؤولية محدودة بمالك واحد، تعمل من دولة الإمارات العربية المتحدة. نقدّم خدماتنا لدعم التواصل التجاري وتسهيل التعارف والتنسيق بين الشركات ومقدمي المنتجات والخدمات والعملاء المحتملين، وفق نطاق الرخصة والتصاريح النظامية ذات الصلة.",
    "vision_title": "رؤيتنا",
    "vision": "أن نكون شريكًا موثوقًا في بناء علاقات تجارية عملية ومستدامة بين الشركات في دولة الإمارات والأسواق الإقليمية والدولية.",
    "mission_title": "رسالتنا",
    "mission": "تسهيل الوصول إلى الفرص التجارية المناسبة عبر التواصل الواضح، وفهم احتياجات الأطراف، ومتابعة التنسيق من التعارف الأولي حتى وضوح الخطوات التالية.",
    "values_title": "قيمنا",
    "values": [
        "الوضوح والنزاهة في التواصل التجاري.",
        "الاستجابة والالتزام بمتابعة ما يتم الاتفاق عليه.",
        "فهم احتياجات العميل قبل اقتراح الحلول.",
        "احترام سرية المعلومات التجارية.",
        "بناء علاقات مهنية طويلة الأمد.",
    ],
    "info_title": "بيانات الشركة",
    "info": [
        ("الاسم التجاري", "B7 Global Brokerage Services (S.P.S - L.L.C)"),
        ("الشكل القانوني", "L.L.C (Sole Proprietorship)"),
        ("المقر", "دولة الإمارات العربية المتحدة"),
        ("المالك", "Bassam Mousa"),
    ],

    "services_eyebrow": "ماذا نقدّم",
    "services_title": "خدماتنا",
    "services_intro": "أربع طرق نساعد بها الشركات على الوصول إلى الطرف المناسب ومتابعة التواصل بفاعلية.",
    "services": [
        ("link", "الوساطة التجارية", "التعريف بين الشركات والأطراف ذات العلاقة، وتنسيق التواصل الأولي وتبادل المعلومات التجارية المتفق عليها."),
        ("briefcase", "تمثيل الشركات", "دعم حضور الشركات وتمثيلها في التواصل التجاري والتعريف بمنتجاتها وخدماتها ضمن نطاق التفويض والرخصة."),
        ("phone", "التسويق عبر الهاتف", "التواصل مع العملاء المحتملين للتعريف بالمنتجات والخدمات وجمع الاهتمام الأولي وترتيب المتابعة."),
        ("swap", "وساطة الخدمات", "ربط العملاء بمزودي الخدمات المناسبين، وتوضيح نطاق الطلب والخطوات المطلوبة بين الأطراف."),
    ],
    "licensed_label": "أنشطتنا المرخصة",
    "licensed": [
        "تمثيل الشركات",
        "التسويق للمنتجات والخدمات عبر الهاتف",
        "وكيل تجاري",
        "وسيط خدمات",
    ],

    "focus_eyebrow": "أين نركّز",
    "focus_title": "مجالات التركيز",
    "focus_intro": "نوجّه خدماتنا بصورة خاصة إلى الشركات والفرص ذات الصلة بالقطاعات الصناعية والتجارية التالية.",
    "focus": [
        ("layers", "المعادن ومواد التعبئة والتغليف", "منتجات الصفيح وغيرها من المنتجات المعدنية، إضافة إلى المواد الأولية والمدخلات الصناعية."),
        ("gear", "الآلات وخطوط الإنتاج", "معدات وخطوط الإنتاج والآلات وقطع الغيار الصناعية."),
        ("box", "مستلزمات التصنيع والتغليف", "مستلزمات التصنيع والتغليف والمنتجات والخدمات المساندة للأعمال الصناعية."),
        ("globe", "التوريد والتوزيع", "فرص التوريد والتوزيع والتعاون بين الشركات داخل دولة الإمارات وخارجها."),
    ],

    "serve_eyebrow": "من نخدم",
    "serve_title": "لكل شركة تشتري أو تبيع أو تبحث عن تمثيل",
    "serve_p": "نخدم المصنّعين والموردين ومقدمي الخدمات والموزعين والمشترين من الشركات، إضافة إلى الشركات التي تبحث عن ممثل تجاري أو قناة تواصل لتطوير حضورها في السوق.",
    "serve_chips": [
        "المصنّعون",
        "الموردون",
        "مقدمو الخدمات",
        "الموزعون",
        "المشترون من الشركات",
        "الشركات الباحثة عن ممثل تجاري",
    ],
    "scope_title": "نطاق العمل",
    "scope_p": "تنطلق الشركة من دولة الإمارات العربية المتحدة، وتدعم فرص التعاون التجاري المحلي وعبر الحدود بحسب طبيعة كل تكليف، وتوفر الأطراف، والمتطلبات التنظيمية المطبقة.",

    "process_eyebrow": "أسلوب العمل",
    "process_title": "خطوات واضحة من أول تواصل حتى الخطوة التالية",
    "process_intro": "نتبع خطوات واضحة تساعد على تنظيم التواصل وحماية توقعات الأطراف.",
    "steps": [
        ("فهم الاحتياج", "تحديد المنتج أو الخدمة المطلوبة، والسوق المستهدف، ومتطلبات العميل الأساسية."),
        ("تحديد الطرف المناسب", "البحث عن مورد أو عميل أو شريك تجاري مناسب بناءً على نطاق التكليف."),
        ("ترتيب التواصل", "تنسيق التعارف وتبادل المعلومات الأولية بعد موافقة الأطراف."),
        ("متابعة النقاط التجارية", "متابعة الاستفسارات والمستندات والخطوات التجارية التي يتفق الأطراف على تبادلها."),
        ("توضيح الخطوات التالية", "تسجيل ما تم الاتفاق عليه ومتابعة الإجراء التالي مع الأطراف المعنية."),
    ],
    "expect_title": "ما الذي يمكن أن تتوقعه من B7 Global",
    "expect": [
        "نقطة تواصل واضحة لمتابعة الطلب التجاري.",
        "تنسيق منظم بين الأطراف وتقليل حالات سوء الفهم.",
        "تعامل مهني يحترم السرية والمعلومات التي يشاركها العميل.",
        "متابعة عملية تتناسب مع نطاق التكليف والأنشطة المرخصة.",
    ],

    "contact_eyebrow": "تواصل معنا",
    "contact_title": "لنتحدث في أعمالكم",
    "contact_p": "أخبرونا بما تبحثون عنه، شراءً أو بيعًا أو تمثيلًا، وسنعود إليكم بخطوات واضحة.",
    "c_person": "جهة التواصل",
    "c_person_v": "Bassam Mousa",
    "c_phone": "الهاتف",
    "c_email": "البريد الإلكتروني",
    "c_whatsapp": "واتساب",
    "c_location": "الموقع",
    "soon": "يُضاف قريبًا",
    "f_name": "الاسم الكامل",
    "f_company": "الشركة",
    "f_email": "البريد الإلكتروني",
    "f_phone": "رقم الهاتف",
    "f_topic": "مجال اهتمامي",
    "f_topics": [
        "الوساطة التجارية",
        "تمثيل الشركات",
        "التسويق عبر الهاتف",
        "وساطة الخدمات",
        "أمر آخر",
    ],
    "f_message": "كيف يمكننا مساعدتكم؟",
    "f_send": "إرسال الطلب",
    "f_sending": "جارٍ الإرسال…",
    "f_required": "يرجى إدخال الاسم والبريد الإلكتروني والرسالة.",
    "f_ok": "شكرًا لكم. تم إرسال طلبكم وسنتواصل معكم قريبًا.",
    "f_mailto": "جارٍ فتح تطبيق البريد لإرسال طلبكم.",
    "f_err": "عذرًا، حدث خطأ ما. يرجى المحاولة مرة أخرى أو التواصل معنا هاتفيًا.",
    "f_notready": "نموذج التواصل الإلكتروني قيد الإعداد. يرجى التواصل معنا هاتفيًا في الوقت الحالي.",
    "f_notready_phone": "نموذج التواصل الإلكتروني قيد الإعداد. يرجى الاتصال بنا على {phone} في الوقت الحالي.",

    "foot_tag": "نربط الأسواق، ونصنع الفرص.",
    "foot_nav": "روابط سريعة",
    "foot_contact": "تواصل معنا",
    "foot_disclaimer": "تلتزم الشركة بممارسة الأعمال ضمن الأنشطة المرخصة لها، واستكمال أي موافقات أو تصاريح لازمة بحسب طبيعة كل معاملة.",
    "foot_rights": "جميع الحقوق محفوظة.",
    "to_top": "العودة إلى الأعلى",
}
